/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 D:\Wisconsin_Madison\Research\LEARNER project\convai_web\ThreeJS\interactiveNPC\vite-project\public\platform.glb 
Author: McWinterL (https://sketchfab.com/winterlea)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/scifi-platform-stage-scene-baked-64adb59a716d43e5a8705ff6fe86c0ce
Title: scifi platform stage scene baked
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/platform.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={[0.1, 0.07, 0.06]}>
      {/* <group scale={0.03}> */}
        <mesh geometry={nodes.Black_Ground_Black_0.geometry} material={materials.Black} position={[-226.264, 508.734, 303.999]} />
        <mesh geometry={nodes['Black_Wall_Black-Wall_0'].geometry} material={materials['Black-Wall']} position={[-226.264, 508.734, 303.999]} />
        <mesh geometry={nodes['Black_LightUpper_Black-Upper_0'].geometry} material={materials['Black-Upper']} position={[-226.264, 508.734, 303.999]} />
        <mesh geometry={nodes.Emissive_Cyan__0.geometry} material={materials.Emissive_Cyan__0} position={[-113.132, 107.464, 152]} />
        <mesh geometry={nodes['Emissive_Red_Emissive-Red_0'].geometry} material={materials['Emissive-Red']} position={[4.632, 438.369, 303.999]} />
        <mesh geometry={nodes['Light_Upper_Light-Upper_0'].geometry} material={materials['Light-Upper']} position={[-461.792, 451.184, 32.134]} />
        <mesh geometry={nodes['3_Wall_Hori_1__0'].geometry} material={materials.Emissive_Cyan__0} position={[0, 474.314, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/platform.glb')
